#!/bin/bash
#SBATCH --job-name=check_hyb
#SBATCH --output=z_job%j.log
#SBATCH --partition=cpu
# #SBATCH --gres=gpu:1
#SBATCH --time=06:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=48
# #SBATCH --MinCPUsNode=8
# #SBATCH --mail-type=ALL
# #SBATCH --mail-user=sujith.ms@students.iiserpune.ac.in

module load python/3.7

python ./inversion.py


