#!/bin/bash
#SBATCH --job-name=nlcg_checker
#SBATCH --output=z_job%j.log
#SBATCH --partition=standard
# #SBATCH --gres=gpu:1
#SBATCH --time=24:00:00
#SBATCH --mem=0
#SBATCH --nodes=1
#SBATCH --ntasks=32
# #SBATCH --MinCPUsNode=8
# #SBATCH --mail-type=ALL
# #SBATCH --mail-user=sujith.ms@students.iiserpune.ac.in

module load python/3.7

python ./inversion.py
